### ISSUE TITLE
Erro na execução

### ISSUE THREAD

**Issue by denisdss** [katomaro/Hotmart-download-bot#5]
Traceback (most recent call last):
File "C:\Users\Work\Documents\Hotmart-download-bot-main\KatoMart.py", line 683, in
verCursos()
File "C:\Users\Work\Documents\Hotmart-download-bot-main\KatoMart.py", line 130, in verCursos
baixarCurso(authMart, cursosValidos[OPCAO], False)
File "C:\Users\Work\Documents\Hotmart-download-bot-main\KatoMart.py", line 316, in baixarCurso
playerInfo = getPlayerInfo(authMart, media)
File "C:\Users\Work\Documents\Hotmart-download-bot-main\KatoMart.py", line 233, in getPlayerInfo
playerConfigurations = playerDom
TypeError: 'NoneType' object is not subscriptable

**Comment by denisdss** [comment]
![image](https://user-images.githubusercontent.com/59034309/135723217-5563c80a-c7f2-4ea0-a41f-5b8078791672.png)

**Comment by ricardosierra** [comment]
@denisdss Arrumou a solução ?

faz um pull request ai
