### ISSUE TITLE
Back error...

### ISSUE THREAD

**Issue by victorpinhors** [katomaro/Hotmart-download-bot#8]
Voltou a dar erro.
Parou ontem, no meio do processo. Faltando algumas aulas ainda.
Reiniciei o equipamento, executei novamente o script. Não tem pasta de log como informa para ser apagada antes de reiniciar o processo.

Erro:

Traceback (most recent call last):
  File "C:\hot\katomart.py", line 618, in parse_course_info
    self.retrieve_native_player_lesson(lesson_info['mediasSrc'])
KeyError: 'mediasSrc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\hot\katomart.py", line 653, in <module>
    HotmartClub()
  File "C:\hot\katomart.py", line 299, in __init__
    self.start_course_download()
  File "C:\hot\katomart.py", line 416, in start_course_download
    self.parse_course_info()
  File "C:\hot\katomart.py", line 620, in parse_course_info
    self.retrieve_embedded_lesson(lesson_info['content'])
KeyError: 'content'

**Comment by katomaro** [comment]
Eu encontrei esse erro uma única vez e fiz um patchzinho na versão que estava usando só pars o download continuarz de madrugada quando eu acordar posso fazer uma commit para não travar nisso. Mas tem que ver por qual motivo esse erro foi estourado, quando eu encontrei era um quiz dentro da plataforma.

Você encontrou esse erro por causa que o script assume que sempre é uma aula, seja em vídeo ou seja textual, a primeira coisa que ele faz por aula é tentar baixar vídeo nativo da plataforma (chave "mediasSrc" do json), se a chave não está presente um erro estoura e ele assume que é vídeo de player externo que vem embeddado na descrição da aula, aí ele chama a função passando ela (chave "content" do json), no seu caso essa chave não existe também, tem como você confirmar se é quiz no seu caso também?

Em todo caso, se quiser destravar de imediato, na linha 621 altere para:
`try:
    self.retrive_embedded_lesson(lesson_info['content'])
except KeyError:
    print(f"Chave content não existente para a aula {self.course_stats['current_lesson']}")`

Quando estourar o erro por causa que a chave não existe no json, ao invés dele travar a execução por completo ele vai falar que deu erro naquela e continuar, não commito agora por causa que acabou a força e eu deitei oara dormir, mas commitaria algo por essas linhas para só não barrar a execução.

Se o erro for causado por quiz mesmo, ta tudo bem, se me recordo não tem muito o que fazer pois eles protegem as repostas corretas no servidor, não sendo útil salvar do meu ponto de vista (mas faz bastante tempo desde que li o json retornado pela api para ver como era quiz), agora, se deu erro sendo aula mesmo é preciso investigar.

**Comment by victorpinhors** [comment]
Desculpe retornar só agora. Ontem era Feriado ( dia das crianças ) e passei com os filhos
Bem, você tem razão. Não existia nada, nem quiz, nem vídeo. somente  o título. Não sei se o autor vai adicionar vídeo mais tarde. 
Bom, fiz a alteração, mas creio que há algum erro na linha que pediu para alterar 
self.retrive_embedded_lesson(lesson_info['content']) except KeyError: print(f"Chave content não existente para a aula {self.course_stats['current_lesson']}")
Pode verificar ?
